valor = input('Digite um valor:')

print(type(valor))
print(valor.isnumeric())
print(valor.isalnum())
print(valor.isalpha())
print(valor.isdecimal())
print(valor.islower())
print(valor.isspace())
print(valor.isupper())
print(valor.isidentifier())
print(valor.isprintable())